version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7d:94:8b:82:92:92:a6:dd:b4:39:4a:bc:e8:b6:4c:0f"
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: funkypenguin/helm-charts
          command: wget -O - https://raw.githubusercontent.com/funkypenguin/helm-github-pages/master/publish.sh | sh
