version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f7:a0:0b:39:77:7b:11:7a:02:c4:61:85:a2:0f:82:ca"
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: funkypenguin/helm-charts
          command: wget -O - https://raw.githubusercontent.com/funkypenguin/helm-github-pages/master/publish.sh | sh
